In [1]:
from numpy.linalg import inv, eig
from numpy.linalg import matrix_rank as rank
from numpy import array, eye, dot, zeros, poly, ones
from numpy import roots, arange, asarray, concatenate
from functools import reduce
import matplotlib.pyplot as plt
from control import acker, place, ss, forced_response
from control import obsv, ctrb, minreal, tf
from IPython.display import Image

def mul_mat(*args):
    return reduce(dot, args)

def plota_resp(T,
               yout,
               titulo,
               xlabel='Tempos (s)',
               ylabel='Altura da bolinha (m)\n'):

    plt.plot(T, yout)
    plt.title(titulo + '\n')
    plt.xlabel('\n' + xlabel)
    plt.ylabel(ylabel + '\n')
    plt.grid(alpha=.5)
    plt.show()
    
def plota_resp_sist(t, yout):
    
    plt.rcParams["figure.figsize"] = (11,7)
    
    fig, axes = plt.subplots(4, 1)
    ylabels = ["x1", "x1'", "x2", "x2'"]

    for num, ax in enumerate(axes.flatten()):
        ax.axhline(y=0, color='black')
        ax.plot(T, yout[num], color='b')
        ax.set_ylabel(ylabels[num])
        ax.grid()

    fig.tight_layout()
    plt.show()    
    
# plots config    
plt.rcParams["figure.figsize"] = (11,7)
plt.rcParams.update({'font.size': 15})


$$ $$
# Aula 13
$$ $$
## Exercício 01
$$ $$

In [23]:
A = array([[0,   1],
           [-2, -2]])

B = array([[1, 3]]).T

C = array([1, 0])

D = 0

In [67]:
A = array([[-2, 1],
           [-2, 0]])

B = array([[1, 3]]).T

C = array([1, 0])

D = 0

In [68]:

# forma controlável
P = array([B, dot(A,B)]).T

P = P.reshape((2,2))

P

array([[ 1,  1],
       [ 3, -2]])

In [69]:
rank(P)

2

Se o rank não é cheio preciso completar com as colunas para obter uma matriz LI.
$$ $$

In [70]:
T = P

A_bar = mul_mat(inv(T),A,T)
B_bar = mul_mat(inv(T),B)
C_bar = mul_mat(C,T)

In [72]:
A_bar.round()

array([[ 0., -2.],
       [ 1., -2.]])

In [73]:
B_bar

array([[1.],
       [0.]])

In [74]:
C

array([1, 0])

In [75]:

# forma controlador
iP = inv(P)
p = iP[1,:] # última linha
 
p

array([ 0.6, -0.2])

In [76]:
aux = array([p, dot(p,A)])
T = inv(aux)

Ac = mul_mat(inv(T),A,T)
Bc = mul_mat(inv(T),B)
Cc = mul_mat(C,T)

In [77]:
Ac

array([[ 0.,  1.],
       [-2., -2.]])

In [79]:
Bc.round()

array([[-0.],
       [ 1.]])

In [80]:
Cc.round()

array([3., 1.])

$$ $$
## Exercício 02
$$ $$

In [81]:
A = array([[-2, 1],
           [-2, 0]])

B = array([[1, 0]]).T

C = array([1, 3])

D = 0

In [82]:

# forma observável
Q = array([C, dot(C,A)])

T = inv(Q)

A_bar = mul_mat(inv(T),A,T)
B_bar = mul_mat(inv(T),B)
C_bar = mul_mat(C,T)

In [83]:
Q

array([[ 1,  3],
       [-8,  1]])

In [85]:
A_bar

array([[ 0.,  1.],
       [-2., -2.]])

In [86]:
B_bar

array([[ 1.],
       [-8.]])

In [87]:
C_bar

array([1., 0.])

In [36]:

# forma controlador
iQ = inv(Q)
q = iP[:,1] # última coluna
 
aux = array([q, dot(A,q)])
QQ = inv(aux)

T = QQ

Ao = mul_mat(inv(T),A,T)
Bo = mul_mat(inv(T),B)
Co = mul_mat(C,T)

In [38]:
Ao.round()

array([[ -1.,   0.],
       [307.,  -4.]])

In [39]:
Bo

array([[0.11764706],
       [4.        ]])