In [1]:
from numpy.linalg import inv, eig
from numpy.linalg import matrix_rank as rank
from numpy import array, eye, dot, zeros, poly, ones
from numpy import roots, arange, asarray, concatenate
from functools import reduce
import matplotlib.pyplot as plt
from control import acker, place, ss, forced_response
from control import obsv, ctrb, minreal, tf, ss2tf, tf2ss
from IPython.display import Image

def mul_mat(*args):
    return reduce(dot, args)

def plota_resp(T,
               yout,
               titulo,
               xlabel='Tempos (s)',
               ylabel='Altura da bolinha (m)\n'):

    plt.plot(T, yout)
    plt.title(titulo + '\n')
    plt.xlabel('\n' + xlabel)
    plt.ylabel(ylabel + '\n')
    plt.grid(alpha=.5)
    plt.show()
    
def plota_resp_sist(t, yout):
    
    plt.rcParams["figure.figsize"] = (11,7)
    
    fig, axes = plt.subplots(4, 1)
    ylabels = ["x1", "x1'", "x2", "x2'"]

    for num, ax in enumerate(axes.flatten()):
        ax.axhline(y=0, color='black')
        ax.plot(T, yout[num], color='b')
        ax.set_ylabel(ylabels[num])
        ax.grid()

    fig.tight_layout()
    plt.show()    
    
# plots config    
plt.rcParams["figure.figsize"] = (11,7)
plt.rcParams.update({'font.size': 15})


In [2]:

# numerador e denominador da função transferência
n = [2, 3, -4]
d = [1, -1, 3, -1]

out = tf2ss(n, d)

In [3]:
out.A.round()

matrix([[ 1.,  3., -1.],
        [-1., -0.,  0.],
        [ 0.,  1.,  0.]])

In [4]:
out.B.round()

matrix([[-1.],
        [ 0.],
        [ 0.]])

In [5]:
out.C.round()

matrix([[-2.,  3., -4.]])

In [6]:
out.D.round()

matrix([[0.]])

$$ $$
# P1
$$ $$

$$ $$
# Controlador 
$$ $$

In [7]:
# Modelo de planta utilizado
A = array([[5,  10],
           [8,  5]])

B = array([[1, 1]]).T

C = array([1, 0])
C2 = array([[1, 0]])

D = array([0])

out = ss2tf(A,B,C,D)

sys = ss (A,B,C,D)

In [8]:
out

TransferFunction(array([1., 5.]), array([  1., -10., -55.]))

In [9]:
# [Ac,Bc,Cc,T] = ctrbf(A,B,C)
# [Ao,Bo,Co,T] = obsvf(A,B,C)

In [10]:
P = array([B, dot(A,B)])

In [11]:
P = P.reshape((2,2)).T

P

array([[ 1, 15],
       [ 1, 13]])

In [12]:
rank(P)

2

In [13]:
T = P

Abar = mul_mat(inv(T), A, T)
Bbar = dot(inv(T), B)
Cbar = dot(C, T)

In [14]:
iP = inv(P)

iP

array([[-6.5,  7.5],
       [ 0.5, -0.5]])

In [15]:
iP[1,:]

array([ 0.5, -0.5])

In [16]:
p = iP[1,:]

iPP=[p, dot(p,A)]

T = inv(iPP)

Ac = mul_mat(inv(T), A, T)

Bc = dot(inv(T), B)

Cc = dot(C, T)

In [17]:
dot(p,A)

array([-1.5,  2.5])

In [18]:
iPP

[array([ 0.5, -0.5]), array([-1.5,  2.5])]

In [19]:
inv(T)

array([[ 0.5, -0.5],
       [-1.5,  2.5]])

In [20]:
T

array([[5., 1.],
       [3., 1.]])

In [21]:
Ac.round()

array([[ 0.,  1.],
       [55., 10.]])

In [22]:
Bc.round()

array([[0.],
       [1.]])

In [23]:
Cc

array([5., 1.])

In [24]:
Kc = array([85, 21])

K = dot(Kc,inv(T))

K = array([K])

K

array([[11., 10.]])

In [25]:
D, V = eig(A-dot(B,K))
D

array([-5., -6.])

In [26]:
A-dot(B,K)

array([[-6.,  0.],
       [-3., -5.]])

In [27]:
# checar pela F. de Ackerman
en = array([0, 1])
phi_des = dot(A,A) + 11*A + 30*eye(2)

phi_des

array([[190., 210.],
       [168., 190.]])

In [28]:
K2 = mul_mat(en, inv(P), phi_des)
K2

array([11., 10.])

In [29]:
inv(P)

array([[-6.5,  7.5],
       [ 0.5, -0.5]])

In [30]:
K==K2

array([[False,  True]])

In [31]:
K2

array([11., 10.])

In [32]:
K

array([[11., 10.]])

$$ $$
# Observador 
$$ $$

In [33]:
Q = array([C, dot(C,A)])

T = inv(Q)

Abar = mul_mat(inv(T), A, T)
Bbar = dot(inv(T), B)
Cbar = dot(C, T)

In [34]:
Q

array([[ 1,  0],
       [ 5, 10]])

In [35]:
rank(Q)

2

In [36]:
iQ = inv(Q)

In [37]:
iQ

array([[ 1. ,  0. ],
       [-0.5,  0.1]])

In [38]:
iQ[:,1]

array([0. , 0.1])

In [39]:
q = iQ[:,1]

QQ = array([q, dot(A,q)]).T
#QQ = array([q, dot(A,q)])

T = (QQ)

Ao = mul_mat(inv(T), A, T)

Bo = dot(inv(T), B)

Co = dot(C, T)

In [40]:
#T.reshape((2,2))
T

array([[0. , 1. ],
       [0.1, 0.5]])

In [41]:
Ao

array([[ 0., 55.],
       [ 1., 10.]])

In [42]:
Bo

array([[5.],
       [1.]])

In [43]:
Co

array([0., 1.])

In [44]:
20*24

480

In [45]:
18+15

33

In [46]:
33+55
270-24.2

245.8

In [47]:
15*18

270

In [48]:
270+55

325

In [49]:
480+55

535

In [50]:
T

array([[0. , 1. ],
       [0.1, 0.5]])

In [51]:
Lo = array([[325, 44]]).T

# inversa
#Lo = array([[245.8, 88]]).T

# ganho 4x
#Lo = array([[535, 55]]).T

Lo

array([[325],
       [ 44]])

In [52]:
L = dot(T,Lo)

L

array([[44. ],
       [54.5]])

In [53]:
L

array([[44. ],
       [54.5]])

In [54]:
A-dot(L,C2)

array([[-39. ,  10. ],
       [-46.5,   5. ]])

In [55]:
C2

array([[1, 0]])

In [56]:
D, V = eig((A-dot(L,C2)))
D.round()

array([-21., -13.])

In [57]:
# checar pela F. de Ackerman
Pbar = array([C.T, dot(A.T,C.T)]).T

Pbar

array([[ 1,  5],
       [ 0, 10]])

In [58]:

en = array([0, 1])
phi_des = dot(A.T,A.T) + 33*A.T + 270*eye(2)

phi_des

array([[540., 344.],
       [430., 540.]])

In [59]:
L = mul_mat(en, inv(Pbar), phi_des)

L

array([43., 54.])

In [60]:
D2 = array([[0]])

a1_ = concatenate((A, B), axis=1)
a2_ = concatenate((C2, D2), axis=1)

AA = concatenate((a1_, a2_), axis=0)


In [61]:
AA

array([[ 5, 10,  1],
       [ 8,  5,  1],
       [ 1,  0,  0]])

In [62]:
# set point é 2
rss = 3
t = array([[0, 0, rss]]).T

t

array([[0],
       [0],
       [3]])

In [63]:
# xss -> 2x1
# uss -> 1x1
# t = [[xss], [uss]]
aux = dot(inv(AA),t)


xss = aux[0:2,:]

# valor de controle
uss = aux[2,:]

In [64]:
inv(AA).round()

array([[  0.,  -0.,   1.],
       [  0.,  -0.,   1.],
       [ -1.,   2., -11.]])

In [65]:
# x1 tem que ficar em 2 e x2 ficar em 3.14
xss

array([[3. ],
       [1.8]])

In [66]:
uss

array([-33.])

In [67]:
K

array([[11., 10.]])

In [68]:
Nx = xss/rss
Nu = uss/rss
Nbar = Nu + dot(K,Nx)

In [69]:
Nu

array([-11.])

In [70]:
Nx

array([[1. ],
       [0.6]])

In [71]:
Nbar = float(Nbar)

In [72]:
Nbar

6.0000000000000036

In [73]:
L2 = array([L]).T

In [74]:



# construindo At
a11 = A - dot(B,K)
a12 = dot(B,K)
a21 = zeros(A.shape)
a22 = A - dot(L2,C2)

a1_ = concatenate((a11, a12), axis=1)
a2_ = concatenate((a21, a22), axis=1)

Ace = concatenate((a1_, a2_), axis=0)

# construindo Bt
b11 = B*Nbar
b21 = zeros(B.shape)

Bce = concatenate((b11, b21), axis=0)

# construindo Ct
c11 = C2
c12 = zeros(C2.shape)

Cce = concatenate((c11, c12), axis=1)


In [75]:
Ace

array([[ -6.,   0.,  11.,  10.],
       [ -3.,  -5.,  11.,  10.],
       [  0.,   0., -38.,  10.],
       [  0.,   0., -46.,   5.]])

In [76]:
Bce

array([[6.],
       [6.],
       [0.],
       [0.]])

In [77]:
Cce

array([[1., 0., 0., 0.]])