# Aula 1
$$ $$

In [1]:
import numpy as np

In [14]:
B = np.array([[0, .5], [-1, .5]])

x = np.array([2, 2])
              
print(f'B: \n{B} \n\nx: \n{x}')

B: 
[[ 0.   0.5]
 [-1.   0.5]] 

x: 
[2 2]


In [18]:
x_ = np.dot(B, x)

x_

array([ 1., -1.])

In [19]:
x_.shape

(2,)

In [28]:
B_1 = np.linalg.inv(B)

(np.dot(B_1, x_) == x).all()

True

$$ $$
## Exercício 1: ex1_base
$$ $$

In [81]:
# base R2 
e1 = np.array([1, 0])
e2 = np.array([0, 1])
base1 = np.array([e1, e2])

e1_ = np.array([1/3, -1/3])
e2_ = np.array([1/3, 1/6])
base2 = np.array([e1_, e2_])

x = np.array([2 ,2])

print(f'Base 1: \n{base1} \n\nBase 2: \n{base2}')

Base 1: 
[[1 0]
 [0 1]] 

Base 2: 
[[ 0.33333333 -0.33333333]
 [ 0.33333333  0.16666667]]


In [82]:
B_col1 = np.dot(np.linalg.inv(base2), e1)
B_col2 = np.dot(np.linalg.inv(base2), e2)

B = np.array([B_col1, B_col2])

B

array([[ 1., -2.],
       [ 2.,  2.]])

In [83]:
x

array([2, 2])

In [84]:
# gabarito x_ = [-2, 8]^T (transposto)
x_ = np.dot(B, x)
x_

array([-2.,  8.])

In [85]:
(np.dot(x_, base2) == x).all()

True