# Aula 3
$$ $$

In [2]:
import numpy as np
import numpy.linalg as la

$$ $$

In [3]:
# método bottom up
A = np.array([[-1, 1], [-1, -3]])
A

array([[-1,  1],
       [-1, -3]])

In [45]:
print(A)

[[-1  1]
 [-1 -3]]


In [47]:
e_vals = la.eig(A)[0]
np.round(e_vals, 2)

array([-2., -2.])

In [52]:
(A - e_vals[0]*np.eye(2)).round()

array([[ 1.,  1.],
       [-1., -1.]])

In [51]:
la.matrix_rank(A - e_vals[0]*np.eye(2))

1

In [55]:
# primeiro autovetor regular
x_1 = np.array([1, -1])
np.dot((A - e_vals[0]*np.eye(2)), x_1).round()

array([-0.,  0.])

In [57]:
# agora preciso gerar o segundo autovetor (generalizado)
x_2 = np.array([1, 0])

# (A - e_vals[0]*eye(2)) * x_2 = x_1
np.dot(A - e_vals[0]*np.eye(2), x_2).round()


array([ 1., -1.])

$$ $$
Após obter os autovetores é possível fazer a matriz de transformação de base.
$$ $$

In [60]:
B = np.array([x_1, x_2]).T
B

array([[ 1,  1],
       [-1,  0]])

In [61]:
# Jordan (diagonalizada)
np.dot(np.dot(la.inv(B), A), B)

array([[-2.,  1.],
       [ 0., -2.]])

In [5]:
la.eig(A)[1].round()

array([[ 1., -1.],
       [-1.,  1.]])

In [7]:
la.inv(la.eig(A)[1]).round()

array([[33554432., 33554431.],
       [33554431., 33554432.]])

In [8]:
np.diag(la.eig(A)[0])

array([[-1.99999998,  0.        ],
       [ 0.        , -2.00000002]])